# Generated by Django 4.2.7 on 2026-05-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/%Y/%m/%d/', verbose_name='Картинка вопроса'),
        ),
        migrations.AlterField(
            model_name='test',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tests/%Y/%m/%d/', verbose_name='Обложка теста'),
        ),
    ]
