# Generated by Django 4.2.7 on 2026-05-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_question_image_alter_test_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='Картинка вопроса (URL)'),
        ),
        migrations.AlterField(
            model_name='test',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='Обложка (URL)'),
        ),
    ]
