# Generated by Django 4.2.7 on 2026-05-04 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0003_alter_question_image_alter_test_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('test', 'Тест'), ('comment', 'Комментарий')], max_length=10, verbose_name='Тип цели')),
                ('target_id', models.IntegerField(verbose_name='ID цели')),
                ('reason', models.TextField(verbose_name='Причина жалобы')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('reviewed', 'Проверено'), ('resolved', 'Решено')], default='pending', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Репорт',
                'verbose_name_plural': 'Репорты',
                'ordering': ['-created_at'],
            },
        ),
    ]
