# Generated by Django 4.2.7 on 2026-05-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_alter_testattempt_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='access_token',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Токен доступа для приватного теста'),
        ),
    ]
