# Generated by Django 4.2.7 on 2026-05-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_test_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='target_type',
            field=models.CharField(choices=[('test', 'Тест'), ('comment', 'Комментарий'), ('user', 'Пользователь')], max_length=10, verbose_name='Тип цели'),
        ),
    ]
