# Generated by Django 4.2.7 on 2026-05-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_alter_report_target_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
    ]
