# Generated by Django 4.2.7 on 2026-05-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_report_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='test_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID теста (для комментариев)'),
        ),
    ]
