# Generated by Django 4.2.7 on 2026-05-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ban_reason',
            field=models.TextField(blank=True, default='', verbose_name='Причина бана'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='Забанен'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_muted',
            field=models.BooleanField(default=False, verbose_name='Замучен'),
        ),
        migrations.AddField(
            model_name='user',
            name='mute_reason',
            field=models.TextField(blank=True, default='', verbose_name='Причина мута'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.TextField(blank=True, null=True, verbose_name='Аватар (URL)'),
        ),
    ]
