# Generated by Django 4.2.7 on 2026-05-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_ban_reason_user_is_banned_user_is_muted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ban_permanent',
            field=models.BooleanField(default=False, verbose_name='Перманентный бан'),
        ),
        migrations.AddField(
            model_name='user',
            name='ban_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Бан до'),
        ),
        migrations.AddField(
            model_name='user',
            name='mute_permanent',
            field=models.BooleanField(default=False, verbose_name='Перманентный мут'),
        ),
        migrations.AddField(
            model_name='user',
            name='mute_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Мут до'),
        ),
    ]
